# Use an official Python runtime as a parent image
FROM python:3.11.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy everything into app folder
COPY . .

# Install requirements and don't cache
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that the app runs on
EXPOSE 5006

CMD alembic upgrade head && gunicorn -b 0.0.0.0:5006 app:app --reload
